package com.wadpam.survey.dao;


import com.wadpam.survey.domain.DQuestion;
import net.sf.mardao.core.CursorPage;

/**
 * Business Methods interface for entity DQuestion.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-19T08:40:22.845+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DQuestionDao extends GeneratedDQuestionDao {

    void setMemCacheEntities(boolean memCacheEntities);

    Iterable<Long> queryKeysByVersion(Object versionKey);

    Iterable<Long> queryKeysBySurvey(Object surveyKey);

    /** return a page of questions sorted by ordering */
    CursorPage<DQuestion> queryPageByVersionSortedByOrdering(Object surveyKey, int pageSize, String cursorString);

}
